baseURL = "https://linasblog.netlify.app"
languageCode = "en-us"
title = "Linas NZ"
theme = "notepadium"
paginate = 20000

[markup.goldmark.renderer]
unsafe = true  # enable raw HTML in Markdown

[params]
mainSections = ['2021', '2022']

[params.nav]
showCategories = true       # /categories/
showTags = false             # /tags/

[[params.nav.custom]]
title = "Diary - older entries"
url = "/categories/diary"

