baseURL = "https://linasblog.netlify.app"
languageCode = "en-us"
title = "Linas NZ"
theme = "notepadium"

[params.nav]
showCategories = true       # /categories/
showTags = false             # /tags/
